# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 520))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setToolTip("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_Port_Selection = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Port_Selection.setMinimumSize(QtCore.QSize(303, 270))
        self.groupBox_Port_Selection.setObjectName("groupBox_Port_Selection")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_Port_Selection)
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_Widget = QtWidgets.QGridLayout()
        self.gridLayout_Widget.setSpacing(6)
        self.gridLayout_Widget.setObjectName("gridLayout_Widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Scan = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.horizontalLayout.addWidget(self.pushButton_Scan)
        self.pushButton_Disc = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Disc.setEnabled(False)
        self.pushButton_Disc.setObjectName("pushButton_Disc")
        self.horizontalLayout.addWidget(self.pushButton_Disc)
        self.gridLayout_Widget.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_Port_Selection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_Widget.addWidget(self.listWidget, 3, 0, 1, 1)
        self.label_Bluetooth = QtWidgets.QLabel(self.groupBox_Port_Selection)
        self.label_Bluetooth.setObjectName("label_Bluetooth")
        self.gridLayout_Widget.addWidget(self.label_Bluetooth, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_11.addLayout(self.gridLayout_Widget)
        self.horizontalLayout_2.addWidget(self.groupBox_Port_Selection)
        self.groupBox_Log = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Log.setMinimumSize(QtCore.QSize(480, 270))
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_Log)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_Log = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Log.setSpacing(6)
        self.horizontalLayout_Log.setObjectName("horizontalLayout_Log")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_Log)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_Log.addWidget(self.textBrowser)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_Log)
        self.horizontalLayout_2.addWidget(self.groupBox_Log)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_Log_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Log_2.setMinimumSize(QtCore.QSize(480, 200))
        self.groupBox_Log_2.setObjectName("groupBox_Log_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_Log_2)
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_Log_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Log_2.setSpacing(6)
        self.horizontalLayout_Log_2.setObjectName("horizontalLayout_Log_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_Log_2)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_Log_2)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Value = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Value.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Value.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_Value.setObjectName("label_Value")
        self.gridLayout_2.addWidget(self.label_Value, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Value_1 = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Value_1.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Value_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_Value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Value_1.setObjectName("label_Value_1")
        self.gridLayout_2.addWidget(self.label_Value_1, 1, 1, 1, 1)
        self.label_Value_3 = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Value_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Value_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_Value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Value_3.setObjectName("label_Value_3")
        self.gridLayout_2.addWidget(self.label_Value_3, 3, 1, 1, 1)
        self.lineEdit_Max_4 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Max_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Max_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Max_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Max_4.setObjectName("lineEdit_Max_4")
        self.gridLayout_2.addWidget(self.lineEdit_Max_4, 4, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_1 = QtWidgets.QSlider(self.groupBox_Log_2)
        self.slider_1.setToolTip("")
        self.slider_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.slider_1.setMaximum(100)
        self.slider_1.setPageStep(1)
        self.slider_1.setProperty("value", 0)
        self.slider_1.setTracking(True)
        self.slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_1.setObjectName("slider_1")
        self.gridLayout_2.addWidget(self.slider_1, 1, 3, 1, 1)
        self.label_Min = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Min.setObjectName("label_Min")
        self.gridLayout_2.addWidget(self.label_Min, 0, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Value_2 = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Value_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Value_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_Value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Value_2.setObjectName("label_Value_2")
        self.gridLayout_2.addWidget(self.label_Value_2, 2, 1, 1, 1)
        self.lineEdit_Min_3 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Min_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Min_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Min_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Min_3.setObjectName("lineEdit_Min_3")
        self.gridLayout_2.addWidget(self.lineEdit_Min_3, 3, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Value_4 = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Value_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Value_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_Value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Value_4.setObjectName("label_Value_4")
        self.gridLayout_2.addWidget(self.label_Value_4, 4, 1, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_Log_2)
        self.checkBox_1.setEnabled(False)
        self.checkBox_1.setStyleSheet("")
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout_2.addWidget(self.checkBox_1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Max_2 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Max_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Max_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Max_2.setObjectName("lineEdit_Max_2")
        self.gridLayout_2.addWidget(self.lineEdit_Max_2, 2, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Min_4 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Min_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Min_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Min_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Min_4.setObjectName("lineEdit_Min_4")
        self.gridLayout_2.addWidget(self.lineEdit_Min_4, 4, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_Max = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Max.setObjectName("label_Max")
        self.gridLayout_2.addWidget(self.label_Max, 0, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Max_3 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Max_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Max_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Max_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Max_3.setObjectName("lineEdit_Max_3")
        self.gridLayout_2.addWidget(self.lineEdit_Max_3, 3, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Max_1 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Max_1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Max_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Max_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Max_1.setObjectName("lineEdit_Max_1")
        self.gridLayout_2.addWidget(self.lineEdit_Max_1, 1, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Min_1 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Min_1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Min_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Min_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Min_1.setObjectName("lineEdit_Min_1")
        self.gridLayout_2.addWidget(self.lineEdit_Min_1, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_Min_2 = QtWidgets.QLineEdit(self.groupBox_Log_2)
        self.lineEdit_Min_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Min_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Min_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Min_2.setObjectName("lineEdit_Min_2")
        self.gridLayout_2.addWidget(self.lineEdit_Min_2, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_Log_2)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.slider_3 = QtWidgets.QSlider(self.groupBox_Log_2)
        self.slider_3.setMaximum(100)
        self.slider_3.setPageStep(1)
        self.slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3.setObjectName("slider_3")
        self.gridLayout_2.addWidget(self.slider_3, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Param = QtWidgets.QPushButton(self.groupBox_Log_2)
        self.pushButton_Param.setEnabled(False)
        self.pushButton_Param.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_Param.setObjectName("pushButton_Param")
        self.horizontalLayout_3.addWidget(self.pushButton_Param)
        self.pushButton_Update = QtWidgets.QPushButton(self.groupBox_Log_2)
        self.pushButton_Update.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_Update.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.horizontalLayout_3.addWidget(self.pushButton_Update)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.slider_2 = QtWidgets.QSlider(self.groupBox_Log_2)
        self.slider_2.setMaximum(100)
        self.slider_2.setPageStep(1)
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setObjectName("slider_2")
        self.gridLayout_2.addWidget(self.slider_2, 2, 3, 1, 1)
        self.slider_4 = QtWidgets.QSlider(self.groupBox_Log_2)
        self.slider_4.setMaximum(100)
        self.slider_4.setSingleStep(1)
        self.slider_4.setPageStep(1)
        self.slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_4.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_4.setObjectName("slider_4")
        self.gridLayout_2.addWidget(self.slider_4, 4, 3, 1, 1)
        self.label_Send = QtWidgets.QLabel(self.groupBox_Log_2)
        self.label_Send.setObjectName("label_Send")
        self.gridLayout_2.addWidget(self.label_Send, 0, 0, 1, 1)
        self.horizontalLayout_Log_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_Log_2)
        self.verticalLayout.addWidget(self.groupBox_Log_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Port_Selection.setTitle(_translate("MainWindow", "Port Selection"))
        self.pushButton_Scan.setText(_translate("MainWindow", "Scan Devices"))
        self.pushButton_Disc.setText(_translate("MainWindow", "Disconnect"))
        self.label_Bluetooth.setText(_translate("MainWindow", "Bluetooth"))
        self.groupBox_Log.setTitle(_translate("MainWindow", "Log"))
        self.groupBox_Log_2.setTitle(_translate("MainWindow", "Regulator"))
        self.label_Value.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Value</p></body></html>"))
        self.label_Value_1.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_Value_3.setText(_translate("MainWindow", "0"))
        self.lineEdit_Max_4.setText(_translate("MainWindow", "1"))
        self.label_Min.setText(_translate("MainWindow", "Min"))
        self.label_Value_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_Min_3.setText(_translate("MainWindow", "0"))
        self.label_Value_4.setText(_translate("MainWindow", "0"))
        self.lineEdit_Max_2.setText(_translate("MainWindow", "1"))
        self.lineEdit_Min_4.setText(_translate("MainWindow", "0"))
        self.label_Max.setText(_translate("MainWindow", "Max"))
        self.lineEdit_Max_3.setText(_translate("MainWindow", "1"))
        self.lineEdit_Max_1.setText(_translate("MainWindow", "1"))
        self.lineEdit_Min_1.setText(_translate("MainWindow", "0"))
        self.lineEdit_Min_2.setText(_translate("MainWindow", "0"))
        self.pushButton_Param.setText(_translate("MainWindow", "Get Parameters"))
        self.pushButton_Update.setText(_translate("MainWindow", "Update Slider Range"))
        self.label_Send.setText(_translate("MainWindow", "Send"))

