# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scope.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 626)
        MainWindow.setMinimumSize(QtCore.QSize(600, 626))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Port_Selection = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Port_Selection.setMinimumSize(QtCore.QSize(480, 290))
        self.groupBox_Port_Selection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Port_Selection.setObjectName("groupBox_Port_Selection")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_Port_Selection)
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_Widget = QtWidgets.QGridLayout()
        self.gridLayout_Widget.setSpacing(6)
        self.gridLayout_Widget.setObjectName("gridLayout_Widget")
        self.listWidget_Serial = QtWidgets.QListWidget(self.groupBox_Port_Selection)
        self.listWidget_Serial.setObjectName("listWidget_Serial")
        self.gridLayout_Widget.addWidget(self.listWidget_Serial, 3, 1, 1, 1)
        self.label_Serial = QtWidgets.QLabel(self.groupBox_Port_Selection)
        self.label_Serial.setObjectName("label_Serial")
        self.gridLayout_Widget.addWidget(self.label_Serial, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Bluetooth = QtWidgets.QLabel(self.groupBox_Port_Selection)
        self.label_Bluetooth.setObjectName("label_Bluetooth")
        self.gridLayout_Widget.addWidget(self.label_Bluetooth, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.listWidget_Bluetooth = QtWidgets.QListWidget(self.groupBox_Port_Selection)
        self.listWidget_Bluetooth.setObjectName("listWidget_Bluetooth")
        self.gridLayout_Widget.addWidget(self.listWidget_Bluetooth, 3, 0, 1, 1)
        self.pushButton_Send = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Send.setEnabled(False)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.gridLayout_Widget.addWidget(self.pushButton_Send, 4, 1, 1, 1)
        self.pushButton_Recv = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Recv.setEnabled(False)
        self.pushButton_Recv.setObjectName("pushButton_Recv")
        self.gridLayout_Widget.addWidget(self.pushButton_Recv, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Scan = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.horizontalLayout.addWidget(self.pushButton_Scan)
        self.pushButton_Disc = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Disc.setEnabled(False)
        self.pushButton_Disc.setObjectName("pushButton_Disc")
        self.horizontalLayout.addWidget(self.pushButton_Disc)
        self.gridLayout_Widget.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Plot = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Plot.setEnabled(True)
        self.pushButton_Plot.setObjectName("pushButton_Plot")
        self.horizontalLayout_2.addWidget(self.pushButton_Plot)
        self.pushButton_Data = QtWidgets.QPushButton(self.groupBox_Port_Selection)
        self.pushButton_Data.setObjectName("pushButton_Data")
        self.horizontalLayout_2.addWidget(self.pushButton_Data)
        self.gridLayout_Widget.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_Widget)
        self.verticalLayout.addWidget(self.groupBox_Port_Selection)
        self.groupBox_Log = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_Log.setMinimumSize(QtCore.QSize(480, 290))
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_Log)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_Log = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Log.setSpacing(6)
        self.horizontalLayout_Log.setObjectName("horizontalLayout_Log")
        self.textBrowser_Recv = QtWidgets.QTextBrowser(self.groupBox_Log)
        self.textBrowser_Recv.setEnabled(True)
        self.textBrowser_Recv.setObjectName("textBrowser_Recv")
        self.horizontalLayout_Log.addWidget(self.textBrowser_Recv)
        self.textBrowser_Send = QtWidgets.QTextBrowser(self.groupBox_Log)
        self.textBrowser_Send.setEnabled(True)
        self.textBrowser_Send.setObjectName("textBrowser_Send")
        self.horizontalLayout_Log.addWidget(self.textBrowser_Send)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_Log)
        self.verticalLayout.addWidget(self.groupBox_Log)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Port_Selection.setTitle(_translate("MainWindow", "Port Selection"))
        self.label_Serial.setText(_translate("MainWindow", "Serial"))
        self.label_Bluetooth.setText(_translate("MainWindow", "Bluetooth"))
        self.pushButton_Send.setText(_translate("MainWindow", "Send to Serial"))
        self.pushButton_Recv.setText(_translate("MainWindow", "Receive from Bluetooth"))
        self.pushButton_Scan.setText(_translate("MainWindow", "Scan Devices"))
        self.pushButton_Disc.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_Plot.setText(_translate("MainWindow", "Plot Figure"))
        self.pushButton_Data.setText(_translate("MainWindow", "Save Data"))
        self.groupBox_Log.setTitle(_translate("MainWindow", "Log"))
